
Import('env')

import sys
import os
import SCons.Script

def run(cmd):
    """Run a command and decipher the return code. Exit by default."""

    res = os.system(cmd)
    # Assumes that if a process doesn't call exit, it was successful
    if( os.WIFEXITED(res)):
    	code = os.WEXITSTATUS(res)
	if code != 0:
	   print "Error: return code: " + str(code)
	   #if SCons.Script.keep_going_on_error == 0:
	   sys.exit(code)

run( env['ENV']['CTPATH'] + '/ct-ng build' )


