obj-$(CONFIG_SPI) += spi.o
obj-$(CONFIG_DRIVER_SPI_IMX) += imx_spi.o
obj-$(CONFIG_DRIVER_SPI_C2K) += c2k_spi.o
obj-$(CONFIG_C2K_SPI_COMMON) += c2k_spi_common.o
obj-$(CONFIG_DRIVER_FAST_SPI_C2K) += c2k_dma.o
obj-$(CONFIG_DRIVER_FAST_SPI_C2K) += c2k_fast_spi.o
obj-$(CONFIG_CSI_FLASH) += csi_flash.o
